import { ReactiveElement } from '../../base/elements.js'
import { html } from '../../deps/lit-html.js'
import gameModel, { STATE_VICTORY } from './game_model.js'
import { START_GAME, PLAY_CARD, END_TURN, STATE_WELCOME, STATE_GAME, STATE_GAME_OVER } from './game_model.js'
import { GameView } from './game_view.js'
