name: Upload To Azure Blob Storage
on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare dist dir
        run: |
          mkdir dist
          cp -r  src test index.html dist

      - uses: bacongobbler/azure-blob-storage-upload@v1.2.0
        with:
          source_dir: 'dist'
          container_name: '$web'
          connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
          sync: true
